### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #i0116

### ISSUE THREAD

**Issue by Z3R0C1PH3R** [Chr0m0s0m3s/DeadTrap#10]
First I was getting the error-
```Running Scan...Traceback (most recent call last):
  File "main.py", line 110, in <module>
    browser.get(f"https://www.truecaller.com/search/{str(answer['country_code']).lower()}/{query.replace('+91', '')}")
KeyError: 'country_code'```

So I found that the API key's monthly limit was over, so I registered and entered my own API key, but now I am getting this error-
```Running Scan...Traceback (most recent call last):
  File "main.py", line 142, in <module>
    email = browser.find_element_by_css_selector('#i0116')
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 627, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 1012, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #i0116```

Please help

**Comment by Z3R0C1PH3R** [comment]
Oh turns out this issue occurs sometimes only- When this issue occurred, I was using protonvpn, does that have any effect on this?

**Comment by Chr0m0s0m3s** [comment]
thats not supposed to happen just checked the css selector is same as it is in the code...i dont understand whats causing this issue...maybe a different web interface is causing the issue

**Comment by Z3R0C1PH3R** [comment]
I dont really know, I can use DeadTrap normally but when I try to use it with protonvpn on, and it throws this error. When I switch off the VPN and the error vanishes... But VPNs should not effect this. Maybe protonvpn does something which interferes with DeadTrap.
OS- Kali Linux- 5.7.0-kali1-amd64
ProtonVPN-CLI v2.2.4
Latest DeadTrap cloned and setup.

**Comment by Chr0m0s0m3s** [comment]
ah i see...i tried it myself with selenium running headless...VPN does have effect on this as it scrpaes most of its results from the web interface...so while running this with vpn it encounters a captcha...hence it couldnt find the css selector...gonna fix the issue soon when i have time...thanks

**Comment by mssalvatore** [comment]
I've run into this without being on a VPN, so there must be other factors that also trigger the captcha.

**Comment by mssalvatore** [comment]
If your IP address is from the USA, TrueCaller wants you to be aware of their cookie policy and to know if you reside in the state of California:

![1](https://user-images.githubusercontent.com/19957806/90462166-45fc3080-e0d6-11ea-9e53-cd5fb65467bd.png)

...


![2](https://user-images.githubusercontent.com/19957806/90462182-4bf21180-e0d6-11ea-8534-43edff35efd3.png)
