### ISSUE TITLE
Traceback Error - Windows 10

### ISSUE THREAD

**Issue by Andrewheis** [Chr0m0s0m3s/DeadTrap#24]
Hey guys and gals,

Trying to get Deadtrap to work on my Windows 10 Machine. Also tried this on my ParrotOS pentest box. No luck. Same error.

`Running Scan...Traceback (most recent call last):
  File "c:\python\python38\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "c:\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python38\Scripts\deadtrap-script.py", line 11, in <module>
    load_entry_point('DeadTrap==0.0.0', 'console_scripts', 'deadtrap')()
  File "c:\python\python38\lib\site-packages\deadtrap\__main__.py", line 185, in main
    browser = webdriver.Firefox(options=optionss)
  File "c:\python\python38\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "c:\python\python38\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

Can someone help? Really digging this tool and want to continue to use it.

**Comment by Chr0m0s0m3s** [comment]
in windows add the path to ur geckodriver executable to ur environment variable that should solve the issue
