### ISSUE TITLE
Country prefix not working

### ISSUE THREAD

**Issue by billpappas77** [Chr0m0s0m3s/DeadTrap#5]
When using country prefix in particular tested for +61 this is the error:

Running Scan...Traceback (most recent call last):
  File "main.py", line 108, in <module>
    browser = webdriver.Firefox(options=optionss)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: connection refused

**Comment by Chr0m0s0m3s** [comment]
are you connected to the internet? seems to me more of a connection issue

**Comment by billpappas77** [comment]
It's working without prefixOn 23 Jun 2020 2:38 pm, Chr0m0s0m3s <notifications@github.com> wrote:
are you connected to the internet? seems to me more of a connection issue

**Comment by billpappas77** [comment]
Without County prefix:
I am running the main.py from virtual box parrot NAT.

See below the results without prefix:
Enter the phone number (along with prefix) :0412******

Running Scan...
Info Scan

------------------------

Valid : False
Number: 04126******
Local Format: 
International Format: 
Country Prefix: 
Country Code: 
Country Name: 
Location: 
Maps : https://www.google.com/maps?q=
Carrier: 
Line Type: None

[*] Scanning Social Media Footprints
-------------------------------------

There is No Facebook account associated with this number
There is No Twitter account associated with this number

^CTraceback (most recent call last):
  File "main.py", line 173, in <module>
    print(linked(query))
  File "/home/user/Downloads/DeadTrap/SocialMedia/scrapelinkedin.py", line 18, in linked
    browser.get('https://www.linkedin.com/checkpoint/rp/request-password-reset')
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 330, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 316, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/remote_connection.py", line 375, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/remote_connection.py", line 398, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt

**Comment by Chr0m0s0m3s** [comment]
Write the country prefix with the number without any space between them

**Comment by billpappas77** [comment]
That's a samle: +61412123708 not real phone. I have tried it without the + but same results. On 23 Jun 2020 4:36 pm, Chr0m0s0m3s <notifications@github.com> wrote:
Write the country prefix with the number without any space between them

**Comment by billpappas77** [comment]
Try this number: +61447240831On 23 Jun 2020 5:24 pm, bill.pappas@hotmail.com wrote:That's a samle: +61412123708 not real phone. I have tried it without the + but same results. On 23 Jun 2020 4:36 pm, Chr0m0s0m3s <notifications@github.com> wrote:
Write the country prefix with the number without any space between them

**Comment by Chr0m0s0m3s** [comment]
Seems like ur machine problem seems to work fine for me

![Screenshot from 2020-06-23 13-07-59](https://user-images.githubusercontent.com/53451298/85374581-a184c480-b552-11ea-98cc-0729e3bab0d0.png)
![Screenshot from 2020-06-23 13-08-04](https://user-images.githubusercontent.com/53451298/85374598-a6497880-b552-11ea-9daa-52b43803419e.png)

**Comment by Chr0m0s0m3s** [comment]
it seems like somehow ur connection is getting refused did you try checking the internet?

**Comment by billpappas77** [comment]
Will try from different VM, I don't know if my internet provider is blocking something.Will investigate from different connection too.On 23 Jun 2020 5:40 pm, Chr0m0s0m3s <notifications@github.com> wrote:
it seems like somehow ur connection is getting refused did you try checking the internet?

**Comment by Chr0m0s0m3s** [comment]
lemme know if u face the same issue there
